#!/usr/bin/env pwsh
$ErrorActionPreference = "Stop"
$rootDir = Resolve-Path "$PSScriptRoot\..\.."
$reportFile = "$rootDir\team\TEST_REPORT_$(Get-Date -Format 'yyyyMMdd_HHmmss').md"

$passed = 0
$failed = 0
$results = @()

function Run-Command {
    param($label, $cwd, $cmd)
    Write-Host "\n=== $label ===" -ForegroundColor Cyan
    Push-Location $cwd
    & $cmd
    $exit = $LASTEXITCODE
    Pop-Location
    $status = if ($exit -eq 0) { $passed++; "PASSED" } else { $failed++; "FAILED" }
    $results += [pscustomobject]@{ Suite = $label; Status = $status; Duration = "~" }
    return $exit
}

# 1. Backend build
Run-Command "Backend Build" "$rootDir\backend" "npm run build"

# 2. Backend unit tests
Run-Command "Backend Unit Tests" "$rootDir\backend" "npm test -- --passWithNoTests --forceExit"

# 3. Frontend type check
Run-Command "Frontend Type Check" "$rootDir\frontend" "npm run type-check"

# 4. Frontend unit tests
Run-Command "Frontend Unit Tests" "$rootDir\frontend" "npm test -- --watchAll=false --passWithNoTests --forceExit"

# 5. Optional E2E smoke (if backend running)
$tcp = New-Object System.Net.Sockets.TcpClient
try {
    $tcp.Connect('localhost', 5000)
    $tcp.Close()
    Run-Command "E2E Smoke Test" "$rootDir\backend" "node scripts/e2e-smoke.js"
} catch {
    Write-Host "Skipping E2E smoke (backend not running)" -ForegroundColor Yellow
}

# Summary report
$date = Get-Date -Format 'dd MMM yyyy HH:mm'
$md = "# Test Report — $date`n`n"
$md += "| Suite | Status | Duration |`n|-------|--------|----------|`n"
foreach ($r in $results) { $md += "| $($r.Suite) | $($r.Status) | $($r.Duration) |`n" }
$md += "`n**Passed:** $passed | **Failed:** $failed`n"
$md += "*Generated by test‑runner.ps1*`n"
$md | Out-File -FilePath $reportFile -Encoding UTF8
Write-Host "Report saved to $reportFile" -ForegroundColor Cyan

if ($failed -gt 0) {
    Write-Host "Tests failed – fix before deployment" -ForegroundColor Red
    exit 1
} else {
    Write-Host "All tests passed" -ForegroundColor Green
    exit 0
}
